graph TD
  Email[Email]
  Email --> Hop1["<<ORIGIN>>"][91.190.155.131 / DB1PEPF00039234.mail.protection.outlook.com]
  Hop1["<<ORIGIN>>"] --> Hop2[2603:10a6:10:469::10 / GVXP194MB2329.EURP194.PROD.OUTLOOK.COM]
  Hop2 --> Hop3[2603:10a6:150:1ff::10 / VI6PPF9F6C943AA.EURP194.PROD.OUTLOOK.COM [MX-internal]]
  Hop3 --> Hop4[2603:10a6:10:469:cafe::c4 / DUZPR01CA0054.outlook.office365.com [MX-internal]]
  Email --> FromDomain[har.com | Reg: None | Created: 1995-11-14T05:00:00Z]